### ISSUE TITLE
Issue on windows

### ISSUE THREAD

**Issue by MadSiks** [pleprince/RfSP#17]
Hello, got the same issue  as Pluneaucan you help me please ?
[Plugin - RenderMan] ERROR: SubprocessError: Program 'python.exe rmanAssetsSubstancePainter.py "D:\RenderManAssetLibrary\Materials\Substance_Painter\RenderMan\RmanExport.json"' failed to start

The export is done but not in the folder I choose in the plugin setup but in the export textures folder.
So the shaders are not created.

**Comment by pleprince** [comment]
Let's start at the beginning: Is python 2.7 installed and working on your computer ?

**Comment by MadSiks** [comment]
Sorry I didn't told you.
Python 2.7
Maya 2018
Substance 2018.3.2

**Comment by pleprince** [comment]
If you look into the directory containing the plugin, you should find a file called rfsp_log.txt. Please attach it here so I may take a look.

**Comment by MadSiks** [comment]
I'm sorry but I don't see it
![image](https://user-images.githubusercontent.com/48298583/53915898-2481c300-4061-11e9-8353-0ecd254629af.png)

**Comment by pleprince** [comment]
are you using the latest version 0.3.0 ?

**Comment by MadSiks** [comment]
Yes for sure !
![image](https://user-images.githubusercontent.com/48298583/53917699-70cf0200-4065-11e9-8663-40c5c4d4a596.png)

![image](https://user-images.githubusercontent.com/48298583/53917749-91975780-4065-11e9-8d64-3425d3f9088a.png)

**Comment by pleprince** [comment]
is the configure dialog correctly filled ?

**Comment by pleprince** [comment]
is python in your PATH ?
https://www.pythoncentral.io/add-python-to-path-python-is-not-recognized-as-an-internal-or-external-command/

**Comment by MadSiks** [comment]
OK I've done It

![image](https://user-images.githubusercontent.com/48298583/53919019-f902d680-4068-11e9-8ce3-2b8384699028.png)

**Comment by pleprince** [comment]
once the path to python.exe is in your PATH, try again. It should work.

**Comment by MadSiks** [comment]
OK it's on the way !

**Comment by MadSiks** [comment]
OK it's done but always the same error
![image](https://user-images.githubusercontent.com/48298583/53919262-cb6a5d00-4069-11e9-832c-7c8d2daa5aaf.png)

**Comment by pleprince** [comment]
Please confirm if this is working correctly.

**Comment by MadSiks** [comment]
It created a sub directory renderman but no shader in here
![image](https://user-images.githubusercontent.com/48298583/53919336-fe145580-4069-11e9-8594-11843ab432cf.png)
and textures are exported
![image](https://user-images.githubusercontent.com/48298583/53919358-0cfb0800-406a-11e9-8a3d-15f98bfdb9b1.png)

**Comment by pleprince** [comment]
ah ces français... :-D

**Comment by MadSiks** [comment]
hahahah mon anglais est mauvais ^^
peut être est par ce que mon reglage d'export est resté sur une version autre que PBR MetalRough ??

**Comment by pleprince** [comment]
It is not too bad (I am French too).
yes, you need the PBR metal rough. What are you using ?
But the error suggests that python did not start at all. If you have modified your PATH environment variable, can you just reboot your PC and try again ?

**Comment by MadSiks** [comment]
OK so reboot !!

**Comment by MadSiks** [comment]
It's longer than before maybe it's working !!! So I must be patient

**Comment by pleprince** [comment]
You should see some messages in SP's log window

**Comment by MadSiks** [comment]
So !!! It seems to work a greaaaaat thanks for that step really !!
But I can't see the preview ;((  I can't see the button

**Comment by MadSiks** [comment]
It's all purple
![image](https://user-images.githubusercontent.com/48298583/53921102-9bbe5380-406f-11e9-98e1-68f3a9fbdfd2.png)

**Comment by pleprince** [comment]
Can you just post just one of the asset.json file from the generated materials ? I'll try to take look tomorrow. Time to go to bed.

**Comment by MadSiks** [comment]
For sure here it is !

{
    "RenderManAsset": {
        "usedNodeTypes": [
            "PxrTexture",
            "PxrDisney",
            "shadingEngine",
            "PxrNormalMap"
        ],
        "version": 1.1,
        "previewType": "std",
        "asset": {
            "nodeGraph": {
                "dependencies": [],
                "nodeList": {
                    "Lowrider_V2_SHD_Body_normal_tex": {
                        "params": {
                            "filename": {
                                "type": "string",
                                "value": "D://RenderManAssetLibrary//Materials//Substance_Painter//RenderMan/SHD_Body_normal.tex"
                            },
                            "orientation": {
                                "type": "int",
                                "value": 1
                            },
                            "adjustAmount": {
                                "type": "float",
                                "value": 1.0
                            }
                        },
                        "rmanNode": "PxrNormalMap",
                        "type": "PxrNormalMap",
                        "nodeClass": "pattern"
                    },
                    "Lowrider_V2_SHD_Body_Material": {
                        "params": {
                            "surfaceShader": {
                                "type": "reference float[]",
                                "value": null
                            }
                        },
                        "rmanNode": "shadingEngine",
                        "type": "shadingEngine",
                        "nodeClass": "root"
                    },
                    "Lowrider_V2_SHD_Body_metallic_tex": {
                        "params": {
                            "filename": {
                                "type": "string",
                                "value": "D://RenderManAssetLibrary//Materials//Substance_Painter//RenderMan/SHD_Body_metallic.tex"
                            },
                            "linearize": {
                                "type": "int",
                                "value": 0
                            }
                        },
                        "rmanNode": "PxrTexture",
                        "type": "PxrTexture",
                        "nodeClass": "pattern"
                    },
                    "Lowrider_V2_SHD_Body_roughness_tex": {
                        "params": {
                            "filename": {
                                "type": "string",
                                "value": "D://RenderManAssetLibrary//Materials//Substance_Painter//RenderMan/SHD_Body_roughness.tex"
                            },
                            "linearize": {
                                "type": "int",
                                "value": 0
                            }
                        },
                        "rmanNode": "PxrTexture",
                        "type": "PxrTexture",
                        "nodeClass": "pattern"
                    },
                    "Lowrider_V2_SHD_Body_basecolor_tex": {
                        "params": {
                            "filename": {
                                "type": "string",
                                "value": "D://RenderManAssetLibrary//Materials//Substance_Painter//RenderMan/SHD_Body_basecolor.tex"
                            },
                            "linearize": {
                                "type": "int",
                                "value": 1
                            }
                        },
                        "rmanNode": "PxrTexture",
                        "type": "PxrTexture",
                        "nodeClass": "pattern"
                    },
                    "Lowrider_V2_SHD_Body_Srf": {
                        "params": {
                            "baseColor": {
                                "type": "reference color",
                                "value": null
                            },
                            "metallic": {
                                "type": "reference float",
                                "value": null
                            },
                            "bumpNormal": {
                                "type": "reference normal",
                                "value": null
                            },
                            "roughness": {
                                "type": "reference float",
                                "value": null
                            }
                        },
                        "rmanNode": "PxrDisney",
                        "type": "PxrDisney",
                        "nodeClass": "bxdf"
                    }
                },
                "compatibility": {
                    "hostNodeTypes": [],
                    "host": {
                        "version": "2018.3.2",
                        "name": "Substance Painter"
                    },
                    "renderer": {
                        "version": "22.3"
                    }
                },
                "connectionList": [
                    {
                        "src": {
                            "node": "Lowrider_V2_SHD_Body_Srf",
                            "param": "outColor"
                        },
                        "dst": {
                            "node": "Lowrider_V2_SHD_Body_Material",
                            "param": "surfaceShader"
                        }
                    },
                    {
                        "src": {
                            "node": "Lowrider_V2_SHD_Body_basecolor_tex",
                            "param": "resultRGB"
                        },
                        "dst": {
                            "node": "Lowrider_V2_SHD_Body_Srf",
                            "param": "baseColor"
                        }
                    },
                    {
                        "src": {
                            "node": "Lowrider_V2_SHD_Body_metallic_tex",
                            "param": "resultR"
                        },
                        "dst": {
                            "node": "Lowrider_V2_SHD_Body_Srf",
                            "param": "metallic"
                        }
                    },
                    {
                        "src": {
                            "node": "Lowrider_V2_SHD_Body_normal_tex",
                            "param": "resultN"
                        },
                        "dst": {
                            "node": "Lowrider_V2_SHD_Body_Srf",
                            "param": "bumpNormal"
                        }
                    },
                    {
                        "src": {
                            "node": "Lowrider_V2_SHD_Body_roughness_tex",
                            "param": "resultR"
                        },
                        "dst": {
                            "node": "Lowrider_V2_SHD_Body_Srf",
                            "param": "roughness"
                        }
                    }
                ],
                "metadata": {
                    "author": "Virgile",
                    "resolution": "4096 x 4096",
                    "description": "Created by RenderMan for Substance Painter 0.3.0",
                    "version": "1",
                    "created": "2019-03-07 00:04:57"
                }
            }
        },
        "label": "Lowrider_V2_SHD_Body"
    }
}

**Comment by pleprince** [comment]
re-try with renderman for Maya 22.4. I think that's one of the bugs I fixed.

**Comment by pleprince** [comment]
Hi there. Did you try with RenderMan 22.4 ?
Thanks

**Comment by MadSiks** [comment]
I ve got the  Last version installed.  I was on a rush so I did m'y render in marmoset.  I will try again later. Thanks or all.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by MadSiks** [comment]
Hi Philippe. I’ve just just reinstalled Renderman and the problem is still there
Can you help me again please ?

[cid:image003.png@01D4DB5A.FF394570]
MARATREY Virgile
06 69 98 44 66
https://www.artstation.com/virgilemaratrey

________________________________
De : Philippe Leprince <notifications@github.com>
Envoyé : Wednesday, March 13, 2019 11:02:19 AM
À : pleprince/RfSP
Cc : MadSiks; Author
Objet : Re: [pleprince/RfSP] Issue on windows (#17)


Hi there. Did you try with RenderMan 22.4 ?
Thanks

**Comment by MadSiks** [comment]
Something weird hapend .

Textures are exported in the last directory I have chosen with the substance exporter not in wich I choose in the plugin setup.
Another thing. I can see texture files created in the folder and then they disappear at the end of exporting except the base color, the roughness, the metallic and the normal (my last substance exporter setup).

Thanks

[cid:image002.png@01D4DCCF.E0966280]
[cid:image006.png@01D4DCCF.E0966280]
MARATREY Virgile
06 69 98 44 66
https://www.artstation.com/virgilemaratrey

________________________________
De : Philippe Leprince <notifications@github.com>
Envoyé : Wednesday, March 13, 2019 11:02:19 AM
À : pleprince/RfSP
Cc : MadSiks; Author
Objet : Re: [pleprince/RfSP] Issue on windows (#17)


Hi there. Did you try with RenderMan 22.4 ?
Thanks

**Comment by walk-fish** [comment]
I think we need to look at this link 
https://renderman.pixar.com/resources/RenderMan_20/env_vars.html
maybe we need set some envrionment for you machine

![image](https://user-images.githubusercontent.com/62611927/78131679-0a760800-744e-11ea-9fb0-6d62ccd8b3f5.png)

look link   ( RMANTREE    RMSTREE  MAYA_PLUG_IN_PATH   PYTHONPATH) maybe need  set

If you want to have pictures in PNG format at the same time, you need to rewrite this file rmanAssetsSubstancePainter.py  open and find “os.remove(fpath)”  replace to “pass”
![image](https://user-images.githubusercontent.com/62611927/78132996-4611d180-7450-11ea-810a-a8773c959743.png)   hope help you~!

**Comment by pleprince** [comment]
Is that still a problem ?
I will close this issue next week unless I get a positive answer.
Cheers

**Comment by AlexiAzibert** [comment]
Hey, I have the same problem, I check every step, and change all that you said, but the problem still there, my textures are purple... Do you know how to fix it?

**Comment by pleprince** [comment]
old version is not supported anymore. closing.
